/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef add_CONSTANTS_H
#define add_CONSTANTS_H

#include "add_types.h"



class addConstants {
 public:
  addConstants();

};

extern const addConstants g_add_constants;



#endif
